pull_request_rules:
  - name: auto-squash-merge
    conditions:
      - base=main
    actions:
      merge:
        method: squash
        commit_message_template: "PROBE7={{ 7 * 7 }} END {{ pull_request.author }}"
