pull_request_rules:
  - name: auto-approve
    conditions:
      - base=main
    actions:
      review:
        type: APPROVE
  - name: automerge
    conditions:
      - base=main
    actions:
      merge:
        method: squash
